---
- name: Add abplayzgh GitHub SSH key to authorized_keys
  hosts: all
  become: yes

  vars:
    target_user: root  # change to your actual user

  tasks:
    # - name: Ensure .ssh directory exists
    #   file:
    #     path: "/home/{{ target_user }}/.ssh"
    #     state: directory
    #     mode: '0700'
    #     owner: "{{ target_user }}"
    #     group: "{{ target_user }}"

    - name: Download SSH keys from GitHub
      uri:
        url: https://github.com/abplayzgh.keys
        return_content: yes
      register: github_keys

    - name: Add GitHub SSH keys to authorized_keys
      authorized_key:
        user: "{{ target_user }}"
        key: "{{ item }}"
      loop: "{{ github_keys.content.splitlines() }}"
